#!/bin/bash

set -eux
set -o errexit
set -o pipefail
set -o nounset

make \
  golines \
  fix \
  fmt \
  shfmt

for FILE in $(git diff --name-status --staged |
  grep --invert-match "D" |
  grep --invert-match "R" |
  cut -d$'\t' -f 2); do
  git add "${FILE}"
done
