formatter: default
rules:
  - body-max-length
  - body-max-line-length
  - body-min-length
  - description-max-length
  - description-min-length
  - footer-enum
  - footer-max-length
  - footer-max-line-length
  - footer-min-length
  - footer-type-enum
  - header-max-length
  - header-min-length
  - scope-charset
  - scope-enum
  - scope-max-length
  - scope-min-length
  - type-charset
  - type-enum
  - type-max-length
  - type-min-length
settings:
  body-max-length:
    argument: -1
  body-max-line-length:
    argument: 72
  body-min-length:
    argument: 0
  description-max-length:
    argument: -1
  description-min-length:
    argument: 0
  footer-enum:
    argument:
      - issue
  footer-max-length:
    argument: -1
  footer-max-line-length:
    argument: 72
  footer-min-length:
    argument: 0
  footer-type-enum:
    argument: []
  header-max-length:
    argument: 50
  header-min-length:
    argument: 10
  scope-charset:
    argument: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/,
  scope-enum:
    argument: []
    flags:
      allow-empty: true
  scope-max-length:
    argument: -1
  scope-min-length:
    argument: 0
  type-charset:
    argument: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
  type-enum:
    argument:
      - build
      - cd
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - test
  type-max-length:
    argument: -1
  type-min-length:
    argument: 0
severity:
  default: error
version: v0.10.0
