issues:
  exclude-rules:
    - linters:
        - cyclop
      path: repository/arvan_channel_repository\.go
    - linters:
        - cyclop
      path: repository/lesson_repository\.go
    - linters:
        - cyclop
      path: repository/package_repository\.go
    - linters:
        - cyclop
      path: repository/user_info_repository\.go
    - linters:
        - gocognit
      path: repository/arvan_channel_repository\.go
    - linters:
        - interfacebloat
      path: config/config\.go
    - linters:
        - interfacebloat
      path: config/log_config\.go
    - linters:
        - interfacebloat
      path: object/dao/arvan_channel\.go
    - linters:
        - interfacebloat
      path: server/server\.go
    - linters:
        - tagliatelle
      path: object/dto/payment_gateway_callback_request\.go
    - linters:
        - tagliatelle
      path: object/om/payment_gateway_callback\.go
  exclude-use-default: false
  fix: true
  max-issues-per-linter: 0
  max-same-issues: 0
linters-settings:
  decorder:
    disable-dec-num-check: false
    disable-dec-order-check: false
    disable-init-func-first-check: false
  depguard:
    additional-guards:
      - include-go-root: false
        list-type: denylist
        packages:
          - github.com/stretchr/testify
    include-go-root: true
    list-type: allowlist
    packages:
      - bytes
      - context
      - crypto/rand
      - database/sql
      - encoding
      - encoding/base64
      - encoding/gob
      - encoding/json
      - errors
      - fmt
      - github.com/ShahoBashoki/kucoin/config
      - github.com/ShahoBashoki/kucoin/helper
      - github.com/ShahoBashoki/kucoin/log
      - github.com/ShahoBashoki/kucoin/middleware
      - github.com/ShahoBashoki/kucoin/object
      - github.com/ShahoBashoki/kucoin/object/dao
      - github.com/ShahoBashoki/kucoin/object/dto
      - github.com/ShahoBashoki/kucoin/object/om
      - github.com/ShahoBashoki/kucoin/repository
      - github.com/ShahoBashoki/kucoin/server
      - github.com/ShahoBashoki/kucoin/service
      - github.com/ShahoBashoki/kucoin/util
      - github.com/dgrijalva/jwt-go
      - github.com/gin-gonic/gin
      - github.com/go-playground/locales/en
      - github.com/go-playground/universal-translator
      - github.com/go-redis/redis/v9
      - github.com/google/uuid
      - github.com/grpc-ecosystem/go-grpc-middleware/tags
      - github.com/spf13/viper
      - go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp
      - go.opentelemetry.io/contrib/propagators/b3
      - go.opentelemetry.io/otel
      - go.opentelemetry.io/otel/codes
      - go.opentelemetry.io/otel/exporters/jaeger
      - go.opentelemetry.io/otel/exporters/stdout/stdouttrace
      - go.opentelemetry.io/otel/propagation
      - go.opentelemetry.io/otel/sdk/resource
      - go.opentelemetry.io/otel/sdk/trace
      - go.opentelemetry.io/otel/semconv/v1.17.0
      - go.opentelemetry.io/otel/trace
      - go.uber.org/zap
      - go.uber.org/zap/zapcore
      - golang.org/x/crypto/bcrypt
      - google.golang.org/grpc/metadata
      - gopkg.in/natefinch/lumberjack.v2
      - gorm.io/driver/postgres
      - gorm.io/gorm
      - gorm.io/gorm/clause
      - gorm.io/gorm/logger
      - gorm.io/gorm/utils
      - io
      - log
      - math/big
      - net/http
      - os
      - path/filepath
      - runtime
      - strconv
      - strings
      - time
  errcheck:
    check-blank: true
    check-type-assertions: true
    disable-default-exclusions: true
    exclude-functions:
      - encoding/json.Marshal
      - encoding/json.MarshalIndent
  errchkjson:
    check-error-free-encoding: true
    report-no-exported: true
  exhaustive:
    check:
      - switch
      - map
    default-signifies-exhaustive: true
    package-scope-only: true
  forbidigo:
    exclude_godoc_examples: false
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(gitlab.playpod.ir/alpha/backend/server-services-next)
      - blank
      - dot
  goconst:
    ignore-calls: false
    numbers: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    settings:
      captLocal:
        paramsOnly: false
      elseif:
        skipBalanced: false
      rangeExprCopy:
        skipTestFuncs: false
      ruleguard:
        failOnError: true
      truncateCmp:
        skipArchDependent: false
      underef:
        skipRecvDeref: false
      unnamedResult:
        checkExported: true
  godot:
    capital: true
    scope: all
  gofmt:
    rewrite-rules:
      - pattern: "a[b:len(a)]"
        replacement: "a[b:]"
      - pattern: "interface{}"
        replacement: any
  gofumpt:
    extra-rules: true
    module-path: gitlab.playpod.ir/alpha/backend/server-services-next
  goimports:
    local-prefixes: gitlab.playpod.ir/alpha/backend/server-services-next
  gomnd:
    ignored-numbers:
      - "0o666"
      - "0o755"
      - "1e2"
      - "1e6"
      - "1e9"
      - "2"
      - "3"
      - "4"
  gomodguard:
    allowed:
      domains:
        - github.com
        - go.opentelemetry.io
        - go.uber.org
        - golang.org
        - google.golang.org
        - gopkg.in
        - gorm.io
    blocked:
      local_replace_directives: true
  gosimple:
    checks:
      - all
  gosec:
    severity: high
    confidence: high
    config:
      G101:
        ignore_entropy: true
      G111:
        pattern: ""
  govet:
    check-shadowing: true
    enable-all: true
    settings:
      shadow:
        strict: true
  grouper:
    const-require-single-const: true
    import-require-single-import: true
    type-require-single-type: true
    var-require-single-var: true
  importas:
    no-extra-aliases: true
    alias:
      - alias: sdkResource
        pkg: go.opentelemetry.io/otel/sdk/resource
      - alias: sdkTrace
        pkg: go.opentelemetry.io/otel/sdk/trace
      - alias: semconv
        pkg: go.opentelemetry.io/otel/semconv/v1.17.0
      - alias: locales
        pkg: github.com/go-playground/locales/en
      - alias: universalTranslator
        pkg: github.com/go-playground/universal-translator
      - alias: stdLog
        pkg: log
      - alias: lumberjack
        pkg: gopkg.in/natefinch/lumberjack.v2
      - alias: grpcTags
        pkg: github.com/grpc-ecosystem/go-grpc-middleware/tags
  loggercheck:
    kitlog: false
    klog: false
    logr: false
    zap: false
    require-string-key: true
    no-printf-like: true
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    require-explanation: true
    require-specific: true
  nonamedreturns:
    report-error-in-defer: true
  prealloc:
    for-loops: true
  predeclared:
    q: true
  promlinter:
    strict: true
  revive:
    confidence: 1
    enable-all-rules: true
    ignore-generated-header: true
    rules:
      - name: add-constant
        severity: error
        disabled: true
        arguments:
          - maxLitCount: "3"
            allowStrs: '"1"'
            allowInts: "0,1"
            allowFloats: ""
      - name: argument-limit
        severity: error
        disabled: true
        arguments:
          - 4
      - name: atomic
        severity: error
        disabled: false
      - name: banned-characters
        severity: error
        disabled: false
        arguments:
          - Ω
          - Σ
          - σ
      - name: bare-return
        severity: error
        disabled: false
      - name: blank-imports
        severity: error
        disabled: false
      - name: bool-literal-in-expr
        severity: error
        disabled: false
      - name: call-to-gc
        severity: error
        disabled: false
      - name: cognitive-complexity
        severity: error
        disabled: true
        arguments:
          - 7
      - name: comment-spacings
        severity: error
        disabled: true
        arguments: []
      - name: confusing-naming
        severity: error
        disabled: false
      - name: confusing-results
        severity: error
        disabled: false
      - name: constant-logical-expr
        severity: error
        disabled: false
      - name: context-as-argument
        severity: error
        disabled: false
        arguments:
          - allowTypesBefore: "*testing.T,*github.com/user/repo/testing.Harness"
      - name: context-keys-type
        severity: error
        disabled: false
      - name: cyclomatic
        severity: error
        disabled: true
        arguments:
          - 3
      - name: datarace
        severity: error
        disabled: false
      - name: deep-exit
        severity: error
        disabled: false
      - name: defer
        severity: error
        disabled: false
        arguments:
          - - call-chain
            - loop
      - name: dot-imports
        severity: error
        disabled: false
      - name: duplicated-imports
        severity: error
        disabled: false
      - name: early-return
        severity: error
        disabled: false
      - name: empty-block
        severity: error
        disabled: false
      - name: empty-lines
        severity: error
        disabled: false
      - name: error-naming
        severity: error
        disabled: false
      - name: error-return
        severity: error
        disabled: false
      - name: error-strings
        severity: error
        disabled: false
      - name: errorf
        severity: error
        disabled: false
      - name: exported
        severity: error
        disabled: false
        arguments:
          - checkPrivateReceivers
          - sayRepetitiveInsteadOfStutters
      - name: file-header
        severity: error
        disabled: true
        arguments:
          - ""
      - name: flag-parameter
        severity: error
        disabled: false
      - name: function-result-limit
        severity: error
        disabled: false
        arguments:
          - 3
      - name: function-length
        severity: error
        disabled: true
        arguments:
          - 10
          - 0
      - name: get-return
        severity: error
        disabled: false
      - name: identical-branches
        severity: error
        disabled: false
      - name: if-return
        severity: error
        disabled: false
      - name: increment-decrement
        severity: error
        disabled: false
      - name: indent-error-flow
        severity: error
        disabled: false
      - name: imports-blacklist
        severity: error
        disabled: false
        arguments:
          - crypto/md5
          - crypto/sha1
      - name: import-shadowing
        severity: error
        disabled: false
      - name: line-length-limit
        severity: error
        disabled: false
        arguments:
          - 120
      - name: max-public-structs
        severity: error
        disabled: true
        arguments:
          - 3
      - name: modifies-parameter
        severity: error
        disabled: false
      - name: modifies-value-receiver
        severity: error
        disabled: false
      - name: nested-structs
        severity: error
        disabled: false
      - name: optimize-operands-order
        severity: error
        disabled: false
      - name: package-comments
        severity: error
        disabled: false
      - name: range
        severity: error
        disabled: false
      - name: range-val-in-closure
        severity: error
        disabled: false
      - name: range-val-address
        severity: error
        disabled: false
      - name: receiver-naming
        severity: error
        disabled: false
      - name: redefines-builtin-id
        severity: error
        disabled: false
      - name: string-of-int
        severity: error
        disabled: false
      - name: string-format
        severity: error
        disabled: false
        arguments:
          - - "core.WriteError[1].Message"
            - "/^([^A-Z]|$)/"
            - must not start with a capital letter
          - - "fmt.Errorf[0]"
            - '/(^|[^\.!?])$/'
            - must not end in punctuation
          - - panic
            - '/^[^\n]*$/'
            - must not contain line breaks
      - name: struct-tag
        severity: error
        disabled: false
      - name: superfluous-else
        severity: error
        disabled: false
      - name: time-equal
        severity: error
        disabled: false
      - name: time-naming
        severity: error
        disabled: false
      - name: var-naming
        severity: error
        disabled: false
        arguments:
          - - ID
          - - VM
      - name: var-declaration
        severity: error
        disabled: false
      - name: unconditional-recursion
        severity: error
        disabled: false
      - name: unexported-naming
        severity: error
        disabled: false
      - name: unexported-return
        severity: error
        disabled: false
      - name: unhandled-error
        severity: error
        disabled: false
        arguments:
          - fmt.Printf
      - name: unnecessary-stmt
        severity: error
        disabled: false
      - name: unreachable-code
        severity: error
        disabled: false
      - name: unused-parameter
        severity: error
        disabled: false
      - name: unused-receiver
        severity: error
        disabled: false
      - name: useless-break
        severity: error
        disabled: false
      - name: waitgroup-by-value
        severity: error
        disabled: false
    severity: error
  rowserrcheck:
    packages:
      - gorm.io/driver/postgres
      - gorm.io/gorm
  staticcheck:
    checks:
      - all
  stylecheck:
    checks:
      - all
    dot-import-whitelist: []
    http-status-code-whitelist: []
    initialisms: []
  tagliatelle:
    case:
      rules:
        avro: snake
        bson: snake
        json: snake
        mapstructure: upper
        xml: snake
        yaml: snake
  tenv:
    all: true
  unparam:
    check-exported: true
  usestdlibvars:
    constant-kind: true
    crypto-hash: true
    default-rpc-path: true
    sql-isolation-level: true
    time-layout: true
    time-month: true
    tls-signature-scheme: true
  varcheck:
    exported-fields: true
  varnamelen:
    check-receiver: true
    check-return: true
    check-type-param: true
    ignore-chan-recv-ok: true
    ignore-decls:
      - fn grpcAuth.AuthFunc
      - gl *gormLog
      - id string
      - id uuid.UUID
      - in map[string]any
      - md *MD
      - ok bool
      - t testing.T
    ignore-map-index-ok: true
    ignore-names:
      - tt
    ignore-type-assert-ok: true
  wrapcheck:
    ignorePackageGlobs:
      - crypto/rand
      - encoding/base64
      - encoding/gob
      - encoding/json
      - fmt
      - github.com/ShahoBashoki/kucoin/object/dao
      - github.com/ShahoBashoki/kucoin/repository
      - github.com/ShahoBashoki/kucoin/server
      - github.com/ShahoBashoki/kucoin/service
      - github.com/ShahoBashoki/kucoin/util
      - github.com/dgrijalva/jwt-go
      - github.com/gin-gonic/gin
      - github.com/go-redis/redis/v9
      - github.com/google/uuid
      - golang.org/x/crypto/bcrypt
      - gorm.io/gorm
      - io
      - net/http
      - strconv
  wsl:
    allow-case-trailing-whitespace: true
    error-variable-names:
      - err
    force-case-trailing-whitespace: 1
    force-err-cuddling: true
linters:
  disable:
    - containedctx
    - dupl
    - errchkjson
    - forcetypeassert
    - funlen
    - goconst
    - ireturn
    - maintidx
    - rowserrcheck # GENERICS
    - wastedassign # GENERICS
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
output:
  format: line-number
  print-issued-lines: false
  sort-results: true
run:
  allow-parallel-runners: true
  modules-download-mode: readonly
  skip-dirs-use-default: false
  skip-dirs:
    - .chglog
    - .devcontainer
    - .githooks
    - .gitlab
    - .vscode
    - api
    - build
    - charts
    - db
    - doc
    - docker
    - gen
    - profile
    - script
    - test/k6
    - vendor
  timeout: 30m
severity:
  default-severity: error
