CREATE TABLE IF NOT EXISTS kucoin_order (
  id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  deleted_at TIMESTAMP,
  channel STRING NOT NULL,
  client_oid STRING NOT NULL,
  deal_funds STRING NOT NULL,
  deal_size STRING NOT NULL,
  fee STRING NOT NULL,
  fee_currency STRING NOT NULL,
  funds STRING NOT NULL,
  kucoin_id STRING NOT NULL,
  kucoin_type STRING NOT NULL,
  op_type STRING NOT NULL,
  price STRING NOT NULL,
  remark STRING NOT NULL,
  side STRING NOT NULL,
  size STRING NOT NULL,
  stop STRING NOT NULL,
  stop_price STRING NOT NULL,
  stp STRING NOT NULL,
  symbol STRING NOT NULL,
  tags STRING NOT NULL,
  time_in_force STRING NOT NULL,
  trade_type STRING NOT NULL,
  visible_size STRING NOT NULL,
  cancel_after INT NOT NULL,
  kucoin_created_at INT NOT NULL,
  cancel_exist BOOL NOT NULL,
  hidden BOOL NOT NULL,
  ice_berg BOOL NOT NULL,
  is_active BOOL NOT NULL,
  post_only BOOL NOT NULL,
  stop_triggered BOOL NOT NULL,
  CONSTRAINT pk PRIMARY KEY (id),
  CONSTRAINT uq_kucoin_id UNIQUE (kucoin_id),
  INDEX ix_created_at (created_at) USING HASH
);

CREATE TABLE IF NOT EXISTS ticker (
  id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  deleted_at TIMESTAMP,
  average_price STRING NOT NULL,
  buy STRING NOT NULL,
  change_price STRING NOT NULL,
  change_rate STRING NOT NULL,
  high STRING NOT NULL,
  last STRING NOT NULL,
  low STRING NOT NULL,
  maker_coefficient STRING NOT NULL,
  maker_fee_rate STRING NOT NULL,
  sell STRING NOT NULL,
  symbol STRING NOT NULL,
  symbol_name STRING NOT NULL,
  taker_coefficient STRING NOT NULL,
  taker_fee_rate STRING NOT NULL,
  vol STRING NOT NULL,
  vol_value STRING NOT NULL,
  CONSTRAINT pk PRIMARY KEY (id),
  CONSTRAINT uq_symbol UNIQUE (symbol),
  INDEX ix_created_at (created_at) USING HASH
);
